version: '3'
services:
#service redis

  redis:
    image: "redis:latest"
    #environment:
    #  REDIS_PASSWORD: "REDIS_PWD"


#service azure-vote

  voting-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    environment:
      - REDIS=redis 
      #- REDIS_PWD="REDIS_PWD"
    restart: always
    depends_on:
      - redis
