- name: Provision Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap Python
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3 python3-pip python3-apt)

    - name: Install nginx
      tasks:
        - name: Get all packages installed
          package_facts:
            manager: auto

        - name: Install Nginx server if missing
          apt:
            name: nginx
            state: present
          when: "'nginx' not in ansible_facts.packages"

        - name: Add index.html
          copy:
            src: index.html
            dest: /usr/share/nginx/html/index.html

- name: Install Flask and Redis
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Flask
      pip:
        name: flask
        state: present
        executable: pip3

    - name: Install Redis server
      apt:
        name: redis-server
        state: present

    - name: Start and enable Redis service
      service:
        name: redis-server
        state: started
        enabled: yes
