name: Release

on:
  push:
    branches:
      - main

jobs:
  ReleaseBuildPush:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0


      - name: linter
        run: pip install pylint

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: linter code
        run: pylint C:\Users\theof\OneDrive\Bureau\voting-app-main\azure-vote\main.py


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}